import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import vm from "node:vm";

const source = readFileSync(new URL("../VideoBackground.js", import.meta.url), "utf8");
const helperBoundary = source.indexOf("const disableYouTubeCaptions");
assert.ok(helperBoundary > 0, "VideoBackground sync helpers must remain before the component helpers");

const context = vm.createContext({});
vm.runInContext(
    `${source.slice(0, helperBoundary)}\n` +
    "globalThis.__videoSyncTest = { getLyricsStartTimeSeconds, getVideoSyncOffsetSeconds, resolveVideoSyncState, wrapVideoSyncTime };",
    context
);

const {
    getLyricsStartTimeSeconds,
    getVideoSyncOffsetSeconds,
    resolveVideoSyncState,
    wrapVideoSyncTime,
} = context.__videoSyncTest;

test("converts the first lyric timestamp from milliseconds", () => {
    assert.equal(getLyricsStartTimeSeconds(57440), 57.44);
    assert.equal(getLyricsStartTimeSeconds(null), null);
});

test("holds Nan-Nan at the first video frame during its negative pre-roll", () => {
    let mapCalls = 0;
    const videoInfo = {
        captionStartTime: 7.591,
        isAutoGenerated: true,
        skipSegments: [],
    };
    const state = resolveVideoSyncState({
        spotifyTime: 0,
        lyricsStartTime: 57.44,
        videoInfo,
        mapVideoTime: () => {
            mapCalls += 1;
            return 999;
        },
    });

    assert.ok(Math.abs(state.baseVideoTime - (-49.849)) < 0.000001);
    assert.equal(state.targetVideoTime, 0);
    assert.equal(state.shouldHoldAtStart, true);
    assert.equal(mapCalls, 0, "skip segments must not move a negative pre-roll away from frame zero");
});

test("maps the first lyric to the registered video anchor", () => {
    const videoInfo = {
        captionStartTime: 7.591,
        isAutoGenerated: true,
        skipSegments: [],
    };
    const state = resolveVideoSyncState({
        spotifyTime: 57.44,
        lyricsStartTime: 57.44,
        videoInfo,
        mapVideoTime: (time) => time,
    });

    assert.ok(Math.abs(state.targetVideoTime - 7.591) < 0.000001);
    assert.equal(state.shouldHoldAtStart, false);
});

test("keeps automatic zero anchors synchronized from the song start", () => {
    const videoInfo = {
        captionStartTime: 0,
        isAutoGenerated: true,
        skipSegments: [],
    };

    assert.equal(getVideoSyncOffsetSeconds(0, 20, videoInfo), 0);
    const state = resolveVideoSyncState({
        spotifyTime: 12,
        lyricsStartTime: 20,
        videoInfo,
        mapVideoTime: (time) => time,
    });
    assert.equal(state.baseVideoTime, 12);
    assert.equal(state.targetVideoTime, 12);
    assert.equal(state.shouldHoldAtStart, false);
});

test("applies skip mapping only after the video timeline begins", () => {
    const videoInfo = {
        captionStartTime: 5,
        skipSegments: [{ start: 10, end: 20 }],
    };
    const state = resolveVideoSyncState({
        spotifyTime: 25,
        lyricsStartTime: 10,
        videoInfo,
        mapVideoTime: (time, segments, anchor) => {
            assert.equal(time, 20);
            assert.equal(segments, videoInfo.skipSegments);
            assert.equal(anchor, 5);
            return 30;
        },
    });

    assert.equal(state.targetVideoTime, 30);
    assert.equal(state.shouldHoldAtStart, false);
});

test("wraps videos that are shorter than the mapped song timeline", () => {
    assert.equal(wrapVideoSyncTime(125, 60), 5);
    assert.equal(wrapVideoSyncTime(30, 60), 30);
    assert.equal(wrapVideoSyncTime(-10, 60), 0);
});
