import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import vm from "node:vm";

const source = readFileSync(new URL("../VideoBackground.js", import.meta.url), "utf8");
const helperBoundary = source.indexOf("const disableYouTubeCaptions");
assert.ok(helperBoundary > 0, "VideoBackground sync helpers must remain before the component helpers");

const context = vm.createContext({});
vm.runInContext(
    `${source.slice(0, helperBoundary)}\n` +
    "globalThis.__videoSyncTest = { getLyricsStartTimeSeconds, getVideoSyncOffsetSeconds, resolveVideoSyncState, wrapVideoSyncTime, syncYouTubePlayerTimeline, settleYouTubeHoldPrime, createVideoSeekState };",
    context
);

const {
    getLyricsStartTimeSeconds,
    getVideoSyncOffsetSeconds,
    resolveVideoSyncState,
    wrapVideoSyncTime,
    syncYouTubePlayerTimeline,
    settleYouTubeHoldPrime,
    createVideoSeekState,
} = context.__videoSyncTest;

test("converts the first lyric timestamp from milliseconds", () => {
    assert.equal(getLyricsStartTimeSeconds(57440), 57.44);
    assert.equal(getLyricsStartTimeSeconds(null), null);
});

test("holds Nan-Nan at the first video frame during its negative pre-roll", () => {
    let mapCalls = 0;
    const videoInfo = {
        captionStartTime: 7.591,
        isAutoGenerated: true,
        skipSegments: [],
    };
    const state = resolveVideoSyncState({
        spotifyTime: 0,
        lyricsStartTime: 57.44,
        videoInfo,
        mapVideoTime: () => {
            mapCalls += 1;
            return 999;
        },
    });

    assert.ok(Math.abs(state.baseVideoTime - (-49.849)) < 0.000001);
    assert.equal(state.targetVideoTime, 0);
    assert.equal(state.shouldHoldAtStart, true);
    assert.equal(mapCalls, 0, "skip segments must not move a negative pre-roll away from frame zero");
});

test("maps the first lyric to the registered video anchor", () => {
    const videoInfo = {
        captionStartTime: 7.591,
        isAutoGenerated: true,
        skipSegments: [],
    };
    const state = resolveVideoSyncState({
        spotifyTime: 57.44,
        lyricsStartTime: 57.44,
        videoInfo,
        mapVideoTime: (time) => time,
    });

    assert.ok(Math.abs(state.targetVideoTime - 7.591) < 0.000001);
    assert.equal(state.shouldHoldAtStart, false);
});

test("keeps automatic zero anchors synchronized from the song start", () => {
    const videoInfo = {
        captionStartTime: 0,
        isAutoGenerated: true,
        skipSegments: [],
    };

    assert.equal(getVideoSyncOffsetSeconds(0, 20, videoInfo), 0);
    const state = resolveVideoSyncState({
        spotifyTime: 12,
        lyricsStartTime: 20,
        videoInfo,
        mapVideoTime: (time) => time,
    });
    assert.equal(state.baseVideoTime, 12);
    assert.equal(state.targetVideoTime, 12);
    assert.equal(state.shouldHoldAtStart, false);
});

test("applies skip mapping only after the video timeline begins", () => {
    const videoInfo = {
        captionStartTime: 5,
        skipSegments: [{ start: 10, end: 20 }],
    };
    const state = resolveVideoSyncState({
        spotifyTime: 25,
        lyricsStartTime: 10,
        videoInfo,
        mapVideoTime: (time, segments, anchor) => {
            assert.equal(time, 20);
            assert.equal(segments, videoInfo.skipSegments);
            assert.equal(anchor, 5);
            return 30;
        },
    });

    assert.equal(state.targetVideoTime, 30);
    assert.equal(state.shouldHoldAtStart, false);
});

test("wraps videos that are shorter than the mapped song timeline", () => {
    assert.equal(wrapVideoSyncTime(125, 60), 5);
    assert.equal(wrapVideoSyncTime(30, 60), 30);
    assert.equal(wrapVideoSyncTime(-10, 60), 0);
});

test("primes a paused YouTube iframe when a backward seek enters negative pre-roll", () => {
    const calls = [];
    const player = {
        getPlayerState: () => 2,
        getCurrentTime: () => 120,
        seekTo: (...args) => calls.push(["seekTo", ...args]),
        playVideo: () => calls.push(["playVideo"]),
        pauseVideo: () => calls.push(["pauseVideo"]),
    };
    const holdState = { isHolding: false, primePending: false };

    syncYouTubePlayerTimeline({
        player,
        targetVideoTime: 0,
        shouldHoldAtStart: true,
        shouldPlay: true,
        holdState,
    });

    assert.deepEqual(calls, [["seekTo", 0, true], ["playVideo"]]);
    assert.deepEqual(holdState, { isHolding: true, primePending: true });
});

test("pauses the YouTube iframe as soon as its refreshed start frame is decoded", () => {
    const calls = [];
    const holdState = { isHolding: true, primePending: true };
    const settled = settleYouTubeHoldPrime({
        player: { pauseVideo: () => calls.push("pauseVideo") },
        playerState: 1,
        holdState,
    });

    assert.equal(settled, true);
    assert.deepEqual(calls, ["pauseVideo"]);
    assert.deepEqual(holdState, { isHolding: true, primePending: false });
});

test("seeks exactly to the mapped time when leaving the held pre-roll", () => {
    const calls = [];
    const player = {
        getPlayerState: () => 2,
        getCurrentTime: () => 0.2,
        seekTo: (...args) => calls.push(["seekTo", ...args]),
        playVideo: () => calls.push(["playVideo"]),
        pauseVideo: () => calls.push(["pauseVideo"]),
    };
    const holdState = { isHolding: true, primePending: false };

    syncYouTubePlayerTimeline({
        player,
        targetVideoTime: 7.591,
        shouldHoldAtStart: false,
        shouldPlay: true,
        holdState,
    });

    assert.deepEqual(calls, [["seekTo", 7.591, true], ["playVideo"]]);
    assert.deepEqual(holdState, { isHolding: false, primePending: false });
});

const makePlayer = (calls, currentTime, state = 1) => ({
    getPlayerState: () => state,
    getCurrentTime: () => currentTime,
    seekTo: (...args) => calls.push(["seekTo", ...args]),
    playVideo: () => calls.push(["playVideo"]),
    pauseVideo: () => calls.push(["pauseVideo"]),
});
const runSync = ({ calls, currentTime, target, seekState, now, holdState = { isHolding: false, primePending: false } }) =>
    syncYouTubePlayerTimeline({
        player: makePlayer(calls, currentTime),
        targetVideoTime: target,
        shouldHoldAtStart: false,
        shouldPlay: true,
        holdState,
        seekState,
        now,
    });

test("tolerates a small drift instead of seeking on every tick", () => {
    const calls = [];
    const seekState = createVideoSeekState();
    runSync({ calls, currentTime: 10.1, target: 10, seekState, now: 5000 });
    assert.deepEqual(calls.filter((call) => call[0] === "seekTo"), []);
});

test("corrects a persistent fine drift only after it holds direction for four samples", () => {
    const calls = [];
    const seekState = createVideoSeekState();
    for (let sample = 0; sample < 3; sample += 1) {
        runSync({ calls, currentTime: 10.3 + sample * 0.25, target: 10 + sample * 0.25, seekState, now: 5000 + sample * 250 });
    }
    assert.deepEqual(calls.filter((call) => call[0] === "seekTo"), [], "three samples are not yet a trend");
    runSync({ calls, currentTime: 11.05, target: 10.75, seekState, now: 5750 });
    assert.deepEqual(calls.filter((call) => call[0] === "seekTo"), [["seekTo", 10.75, true]]);
});

test("learns the seek latency and compensates the next seek", () => {
    const calls = [];
    const seekState = createVideoSeekState();
    // A big drift forces a seek at t=0.
    runSync({ calls, currentTime: 20, target: 10, seekState, now: 0 });
    assert.deepEqual(calls.at(-1), ["seekTo", 10, true]);
    // One second later the video still sits 0.3s behind the target: the seek landed late.
    runSync({ calls, currentTime: 10.7, target: 11, seekState, now: 1000 });
    assert.ok(Math.abs(seekState.seekBias - 0.15) < 1e-9, `bias should move half the residual, got ${seekState.seekBias}`);
    // The next forced seek aims slightly ahead to absorb that latency.
    runSync({ calls, currentTime: 40, target: 30, seekState, now: 5000 });
    assert.deepEqual(calls.at(-1), ["seekTo", 30.15, true]);
});

test("does not seek again right after a seek unless the drift is severe", () => {
    const calls = [];
    const seekState = createVideoSeekState();
    runSync({ calls, currentTime: 20, target: 10, seekState, now: 0 });
    runSync({ calls, currentTime: 9.2, target: 10, seekState, now: 300 });
    assert.equal(calls.filter((call) => call[0] === "seekTo").length, 1, "a 0.8s drift 300ms after seeking is buffering, not drift");
    runSync({ calls, currentTime: 5, target: 10, seekState, now: 400 });
    assert.equal(calls.filter((call) => call[0] === "seekTo").length, 2, "a 5s drift is corrected immediately");
});
